name: kmasc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  mobile_scanner: ^5.2.3

  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  http: ^1.2.0
  lzstring: ^2.0.0
  flutter_pdfview: ^1.3.2
  syncfusion_flutter_pdfviewer: 27.1.52
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/KMA_logo.png
    - assets/images/img1.png
    - assets/images/img2.png
    - assets/images/img3.png
    - assets/images/degree_sample.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/KMA_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/KMA_logo.png"
